name: Deploy to Github Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: AlienKevin/flutter-gh-pages@v11
        with:
          webRenderer: canvaskit
          baseHref: /${{ github.event.repository.name }}/